### ISSUE TITLE
future_lapply(): Please use future_lapply() of the future.apply package

### ISSUE THREAD

**Issue by HenrikBengtsson** [tlverse/origami#28]
Hi, [future 1.7.0](https://cran.r-project.org/package=future) is now on CRAN and I'm now starting the process of deprecating the usage `future::future_lapply()`, which has moved to the [future.apply](https://cran.r-project.org/package=future.apply) package.  Please upgrade your code to use:
```r
importFrom(future.apply, future_lapply)
```
or
```r
future.apply::future_lapply()
```
This should be a straightforward update without any surprises.

In the next release of the future package, `future::future_lapply()` will produce a formal "deprecated" warning and in the release after that it will produce a "defunct" error.

**Comment by jeremyrcoyle** [comment]
Thanks for the heads up. @nhejazi is working on a new cran release for `origami` right now, so we'll get this changed quickly.

**Comment by nhejazi** [comment]
Awesome! Thanks for the heads-up @HenrikBengtsson. This migration has been taken care of as of 
098a7e4, currently a part of #27 (to be merged prior to the upcoming CRAN re-release).

**Comment by jeremyrcoyle** [comment]
Fixed in https://github.com/tlverse/origami/pull/27 . Thanks @nhejazi . Will submit to CRAN today.
