### ISSUE TITLE
future::values() is defunct and will soon to be removed

### ISSUE THREAD

**Issue by HenrikBengtsson** [tlverse/origami#63]
Hi. You use

https://github.com/tlverse/origami/blob/e1b8fe6f5e75fff1d48eed115bb81475c9bd506e/NAMESPACE#L39

Searching your code, it doesn't look like you're actually calling `values()`, so I think you can drop it.  If you do use `values()` somewhere, please use `value()` from **future** instead; it's 100%-backward compatible.

`values()` has been defunct since future 1.23.0 (2021-10-30) and deprecated since future 1.20.0 (2020-10-30).  Now, I'd like to remove `values()` completely from **future** to clean up the API.  I'd appreciate if you could fix this sooner rather than later.  Thanks.

**Comment by nhejazi** [comment]
thanks for pointing this out @HenrikBengtsson and for checking that `future::values` isn’t used in the package’s codebase. I’ll take a closer look and replace `values` with `value` in any instances I catch. A PR closing this issue should be completed by tomorrow.

**Comment by nhejazi** [comment]
[4f34caf](https://github.com/tlverse/origami/commit/4f34caf7fb440224e5bc7dca45ea1dbf65cb8f3f) resolves this. It has been added to `devel` and will soon be merged to `master`.

**Comment by HenrikBengtsson** [comment]
Thanks. Do you have an ETA for when you'll be submitting the updated version to CRAN?

**Comment by jeremyrcoyle** [comment]
It should be on CRAN now. Sorry for the delay.

**Comment by HenrikBengtsson** [comment]
Perfect. Thx
